T=int(input())
for _ in range(T):
    test_case, length=input().split()
    string=input()
    result='ZRO '*string.count('ZRO')
    result+='ONE '*string.count('ONE')
    result += 'TWO ' * string.count('TWO')
    result += 'THR ' * string.count('THR')
    result += 'FOR ' * string.count('FOR')
    result += 'FIV ' * string.count('FIV')
    result += 'SIX ' * string.count('SIX')
    result += 'SVN ' * string.count('SVN')
    result += 'EGT ' * string.count('EGT')
    result += 'NIN ' * string.count('NIN')
    print(test_case)
    print(result)